# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1105, 1850)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_recentlyPlayed = QtWidgets.QLabel(self.centralwidget)
        self.label_recentlyPlayed.setGeometry(QtCore.QRect(14, 5, 531, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_recentlyPlayed.setFont(font)
        self.label_recentlyPlayed.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_recentlyPlayed.setObjectName("label_recentlyPlayed")
        self.label_musicLib = QtWidgets.QLabel(self.centralwidget)
        self.label_musicLib.setGeometry(QtCore.QRect(560, 5, 531, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_musicLib.setFont(font)
        self.label_musicLib.setStyleSheet("background-color: rgb(255,255,255)")
        self.label_musicLib.setObjectName("label_musicLib")
        self.searchBar = QtWidgets.QLineEdit(self.centralwidget)
        self.searchBar.setGeometry(QtCore.QRect(552, 81, 541, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.searchBar.setFont(font)
        self.searchBar.setObjectName("searchBar")
        self.list_recentlyPlayed = QtWidgets.QListWidget(self.centralwidget)
        self.list_recentlyPlayed.setGeometry(QtCore.QRect(15, 71, 531, 851))
        self.list_recentlyPlayed.setObjectName("list_recentlyPlayed")
        self.list_musicLib = QtWidgets.QListWidget(self.centralwidget)
        self.list_musicLib.setGeometry(QtCore.QRect(555, 181, 541, 741))
        self.list_musicLib.setObjectName("list_musicLib")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1105, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_recentlyPlayed.setText(_translate("MainWindow", "Recently Played"))
        self.label_musicLib.setText(_translate("MainWindow", "Music Library"))
        self.searchBar.setPlaceholderText(_translate("MainWindow", "Search For A Song"))
